set(CMAKE_Fortran_COMPILER "/usr/sw/mpi/mpi_20220608_SEA/bin/mpif90" CACHE STRING "")
set(CMAKE_Fortran_FLAGS "-O3 -g -ffree-line-length-none -mieee " CACHE STRING "")
# set(Fortran_MIN_FLAGS "-O0 -g" CACHE STRING "")
set(CMAKE_C_COMPILER "/usr/sw/mpi/mpi_20220608_SEA/bin/mpicc" CACHE STRING "")
set(CMAKE_C_FLAGS "-c -std=gnu99 -O3 -g -mieee" CACHE STRING "")
# set(CMAKE_CXX_COMPILER "mpicxx" CACHE STRING "")
# set(CMAKE_CXX_FLAGS "-c -O3 -g -mieee" CACHE STRING "")
set(LIB_PATHS "/home/export/base/shisuan/swyjs/lxh/lib/xMath_20201223_g" CACHE STRING "")
set(LIBS "swlapack swblas swscalapack" CACHE STRING "")
set(ARCHITECTURE "Generic" CACHE STRING "")
set(USE_MPI ON CACHE BOOL "")
set(USE_SCALAPACK ON CACHE BOOL "")
set(USE_C_FILES ON CACHE BOOL "")
# set(USE_CXX_FILES ON CACHE BOOL "")
set(USE_SPGLIB ON CACHE BOOL "")
set(USE_LIBXC ON CACHE BOOL "")
set(USE_HDF5 OFF CACHE BOOL "")
set(USE_RLSY ON CACHE BOOL "")
set(USE_iPI OFF CACHE BOOL "")
set(USE_OPENCL ON CACHE BOOL "")

# set(LINK_FLAGS " -mhybrid -lm_slave ")