set(CMAKE_Fortran_COMPILER "mpif90" CACHE STRING "")
set(CMAKE_Fortran_FLAGS "-O3 -g -ffree-line-length-none -march=native" CACHE STRING "")
# set(Fortran_MIN_FLAGS "-O0 -g" CACHE STRING "")
set(CMAKE_C_COMPILER "mpigcc" CACHE STRING "")
set(CMAKE_C_FLAGS "-c -std=gnu99 -O3 -g -march=native" CACHE STRING "")
set(CMAKE_CXX_COMPILER "mpicxx" CACHE STRING "")
set(CMAKE_CXX_FLAGS "-c -O3 -g -march=native" CACHE STRING "")
set(LIB_PATHS "/public/software/compiler/intel/oneapi/mkl/2021.3.0/lib/intel64" CACHE STRING "")
set(LIBS "mkl_intel_lp64 mkl_sequential mkl_core mkl_blacs_intelmpi_lp64 mkl_scalapack_lp64" CACHE STRING "")
set(ARCHITECTURE "AMD64_AVX" CACHE STRING "")
# set(ARCHITECTURE "Generic" CACHE STRING "")
set(USE_MPI ON CACHE BOOL "")
set(USE_SCALAPACK ON CACHE BOOL "")
set(USE_C_FILES ON CACHE BOOL "")
set(USE_CXX_FILES ON CACHE BOOL "")
set(USE_SPGLIB ON CACHE BOOL "")
set(USE_LIBXC ON CACHE BOOL "")
set(USE_HDF5 OFF CACHE BOOL "")
set(USE_RLSY ON CACHE BOOL "")
set(USE_iPI OFF CACHE BOOL "")
set(USE_OPENCL ON CACHE BOOL "")
